//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAURANT_AUTOMATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ORDERDETAILS = new HashSet<ORDERDETAILS>();
        }
    
        public int ID { get; set; }
        public int ODEMESEKLIID { get; set; }
        public int MUSTERIID { get; set; }
        public string ORDERNUMBER { get; set; }
        public System.DateTime ORDERDATE { get; set; }
        public decimal FINALTOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAILS> ORDERDETAILS { get; set; }
    }
}
