//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAURANT_AUTOMATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS
    {
        public int TRANSACTIONID { get; set; }
        public int ITEMID { get; set; }
        public decimal QUANTITY { get; set; }
        public System.DateTime TRANSACTIONDATE { get; set; }
        public Nullable<int> TYPEID { get; set; }
    }
}
